### PR TITLE
Danieljgroso manage script names

### PR DESCRIPTION
**Pull request by danieljgroso**
# Description

 

I updated the scripts to reflect the order in which they're called by the pipeline.

Fixes # 4

## Type of change

 

N/A, cosmetic / non-functional change

# How Has This Been Tested?

 

N/A, cosmetic / non-functional change
# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by cansavvy** [comment]
This is a great start! However we'll also need to update the references to these files in the Snakefile. Can you try to add that to this pull request?

**Comment by danieljgroso** [comment]
@cansavvy will do, thanks for catching that!

edit: done

**Comment by howardbaik** [comment]
@danieljgroso @cansavvy Is this ready to be merged?

**Comment by cansavvy** [comment]
We ended up making a separate repo: https://github.com/FredHutch/gimap So we don't have to merge this. But we can.

**Pull request merged**
